; xinput -list | grep -i key
; setxkbmap -device 8 lo

; A1 (ົ)
(global-set-key (kbd "ົ") 'kmacro-start-macro)
; A2 (ໄ)
(global-set-key (kbd "ໄ") 'bm-toggle)
; A3 (ຳ)
(global-set-key (kbd "ຳ") 'newline)
; A4 (ພ)
(global-set-key (kbd "ພ") 'narrow-to-region)
; A5 (ະ)
(global-set-key (kbd "ະ") 'copy-to-register-1)
; A6 (ິ)
(global-set-key (kbd "ິ") 'unfill-paragraph)
; A7 (ີ)
(global-set-key (kbd "ີ") (lambda () (interactive) (insert ":TIMESTAMP:")))
; A8 (ຄ)
(global-set-key (kbd "ຄ")
 (lambda ()
   (interactive)
   (ispell-change-dictionary "brasileiro")))
; A9 (ຕ)
(global-set-key (kbd "ຕ")
 (lambda ()
   (interactive)
   (ispell-change-dictionary "american")))
; A0 (ຈ)
(global-set-key (kbd "ຈ") 'flyspell-mode)

; B1 (ັ)
(global-set-key (kbd "ັ") 'kmacro-end-macro)
; B2 (ຫ)
(global-set-key (kbd "ຫ") 'bm-next)
; B3 (ກ)
; defined localy in gertec_code
; B4 (ດ)
(global-set-key (kbd "ດ") 'widen)
; B5 (ຣ)
(global-set-key (kbd "ຣ") 'paste-from-register-1)
; B6 (ນ)
(global-set-key (kbd "ນ") 'org-agenda-list)
; B7 (ຍ)
(global-set-key (kbd "ຍ") 'enlarge-window-horizontally)
; B8 (ຖ)
(global-set-key (kbd "ຖ") 'ispell-word)
; B9 (ຸ)
(global-set-key (kbd "ຸ") 'flyspell-buffer)
; B0 (ູ)
(global-set-key (kbd "ູ") 'newline)

; C1 (ຜ)
(global-set-key (kbd "ຜ") 'kmacro-end-and-call-macro)
; C2 (ປ)
(global-set-key (kbd "ປ") 'scroll-down-other-window)
; C3 (ເ)
(global-set-key (kbd "ເ") 'page-down-other-window)
; C4 (້)
(global-set-key (kbd "້") 'other-window)
; C5 (່)
(global-set-key (kbd "່") (lambda () (interactive) (ucs-insert 231)))
; C6 (າ)
(global-set-key (kbd "າ") 'TeX-fold-clearout-paragraph)
; C7 (ສ)
(global-set-key (kbd "ສ") 'delete-trailing-whitespace)
; C8 (ຢ)
(global-set-key (kbd "ຢ") 'set-frame-size-according-to-resolution-vertical)
; C9 (ຟ)
(global-set-key (kbd "ຟ") 'magit-status)
; C0 (ໂ)
(global-set-key (kbd "ໂ") 'gnus)

; D2 (ແ)
(global-set-key (kbd "ແ") 'scroll-up-other-window)
; D3 (ອ)
(global-set-key (kbd "ອ") 'page-up-other-window)
; D4 (ຶ)
(global-set-key (kbd "ຶ") 'kill-buffer-in-other-window)
; D5 ()
;(global-set-key (kbd "") 'newline)
; D6 (ື)
(global-set-key (kbd "ື") 'previous-user-buffer)
; D7 (ທ)
(global-set-key (kbd "ທ") 'next-user-buffer)
; D8 ()
;(global-set-key (kbd "") 'newline)
; D9 (ຂ)
(global-set-key (kbd "ຂ") '(lambda () (interactive) (command-execute 'eval-expression)))
; D0 ()
;(global-set-key (kbd "") 'newline)

